# Generated by Django 4.0.4 on 2022-06-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('idPlanta', models.IntegerField(primary_key=True, serialize=False, verbose_name='id planta')),
                ('tipoPlanta', models.CharField(max_length=20, verbose_name='Tipo de planta')),
                ('nombrePlanta', models.CharField(max_length=50, verbose_name='Nombre planta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
