# Generated by Django 4.0.5 on 2022-07-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plantas_imagenplanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantas',
            name='costoPlanta',
            field=models.IntegerField(max_length=50, null=True, verbose_name='Costo planta'),
        ),
    ]
