# Generated by Django 4.0.4 on 2022-07-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plantas_costoplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='User')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
            ],
        ),
    ]
